export default class Constants {
  static SDK_ACTIONS = {
    BACK_TO_SERVICES: "BACK_TO_SERVICES",
    BACK_TO_HOME: "BACK_TO_HOME",
    CARD_LIST: "CARD_LIST",
    CHECK_ACTIVE_TOKEN: "CHECK_ACTIVE_TOKEN",
    SIMULATE_CHECKOUT: "SIMULATE_CHECKOUT",
    GET_REGISTRATION_DATA_COMPLETE: "GET_REGISTRATION_DATA_COMPLETE",
    OPEN_LINK: "OPEN_LINK",
  };

  static SDK_CATEGORIES = {
    DEFAULT: "DEFAULT",
  };

  static SDK_CUSTOMER_KEYS = {
    APP_ID: "APP_ID",
    CUSTOMER_CPF: "CUSTOMER_CPF",
    CUSTOMER_FULL_NAME: "CUSTOMER_FULL_NAME",
    CUSTOMER_ACCESSIBILITY: "CUSTOMER_ACCESSIBILITY",
    PLATFORM: "PLATFORM",
    CUSTOMER_EMAIL: "CUSTOMER_EMAIL",
    CUSTOMER_TYPE: "CUSTOMER_TYPE",
    TOKEN: "TOKEN",
    SALTY: "SALTY",
    AUTHENTICATION: "AUTHENTICATION",
    CUSTOMER_CARD_NAME: "CUSTOMER_CARD_NAME",
    CUSTOMER_CARD_FLAG: "CUSTOMER_CARD_FLAG",
    CUSTOMER_CARD_TYPE: "CUSTOMER_CARD_TYPE",
    CUSTOMER_CARD_PRODUCT: "CUSTOMER_CARD_PRODUCT",
    CUSTOMER_CARD_OWNERSHIP: "CUSTOMER_CARD_OWNERSHIP",
    APP_NAME: "APP_NAME",
    CUSTOMER_CPF_HASHED: "CUSTOMER_CPF_HASHED",
    PLATFORM_VERSION: "PLATFORM_VERSION",
    ACCOUNT_SEGMENT: "ACCOUNT_SEGMENT",
    CUSTOMER_AGENCY: "CUSTOMER_AGENCY",
    CUSTOMER_ACCOUNT: "CUSTOMER_ACCOUNT",
    CUSTOMER_ACCOUNT_DAC: "CUSTOMER_ACCOUNT_DAC",
    NOT_ACCOUNT_HOLDER: "NOT_ACCOUNT_HOLDER",
  };
}
